### ISSUE TITLE
XBMC Watched Command (W?) Activates Favorite for a Game

### ISSUE THREAD

**Issue by GoogleCodeExporter** [maloep/romcollectionbrowser#148]
```
XBMC Watched Command (W?) Activates Favorite for a Game - fairly 
straightforward and simple (idea at least - code wise I don't know).  Basically 
just press W or your remote key and a single game becomes tagged as a favorite 
or untagged as a favorite.

```

Original issue reported on code.google.com by `razam...@gmail.com` on 16 May 2013 at 2:04

**Comment by maloep** [comment]
Might be worth to consider general support for shortcuts. Right now there is only "C" for context menu and "I" Info dialog.

There could be shortcuts for Import games, Add/Remove favorite and maybe others.

**Comment by maloep** [comment]
Done with 0f28e8493063131ca155f61987c3b64662cdf1e7

Current shortcuts:
R: Filter Rom Collection
F: Add/Remove Game to/from favorites
CTRL+F: Add/Remove Selection to/from favorites
