### ISSUE TITLE
Enhancement Request: Sort systems A-Z

### ISSUE THREAD

**Issue by GoogleCodeExporter** [maloep/romcollectionbrowser#181]
```
Systems seem to be always listed by ID or otherwise. Can we have an option or 
default to sort the system names?

```

Original issue reported on code.google.com by `mdegu...@gmail.com` on 7 Sep 2014 at 1:49

**Comment by bruny** [comment]
The quickest way to do this for the drop-down filter is to add the following line to gui.py:showConsoles():

`
# Sort the consoles by name
consoles = sorted (consoles, key=lambda console: console[1])
		
self.showFilterControl(consoles, CONTROL_CONSOLES, showEntryAllItems, rcDelete, rDelete, True)
`

**Comment by nitro322** [comment]
thanks, bruny!  This issue has been bothering me for a couple years.  Even tried fixing it myself once before, but I'm just terrible with python.  Really, really appreciate the tip.  Hope this can make it into an official release soon.

**Comment by maloep** [comment]
Fixed in https://github.com/maloep/romcollectionbrowser/commit/536e2dcf2b5f5bb8fec933b25a109d25abf1055c
