### ISSUE TITLE
Prevent Cmd window to pop up when loading game

### ISSUE THREAD

**Issue by GoogleCodeExporter** [maloep/romcollectionbrowser#211]
```
When you execute games, windows cmd window will pop up. I would like not the 
this on top of screen. Thanks for your great work. Rcb rocks!
Sorry for double post.
```

Original issue reported on code.google.com by `Mediu...@googlemail.com` on 22 Mar 2015 at 10:37

**Comment by maloep** [comment]
Popen option is not in Addon settings. It is located in Edit Rom Collection dialog on Launch Games tab.
