### ISSUE TITLE
Rom Collection Browser for iOS ipad iphone

### ISSUE THREAD

**Issue by GoogleCodeExporter** [maloep/romcollectionbrowser#215]
```
Is it possible to get Rom Collection Browser on ios devices ,or advanced 
launcher?
```

Original issue reported on code.google.com by `sonna22...@gmail.com` on 14 Apr 2015 at 2:58

**Comment by bruny** [comment]
I'd suspect the chances for getting this up and running are slim to none based on this: http://kodi.wiki/view/HOW-TO:Install_Kodi_for_iOS

Future maintenance would be a big issue too - installing Kodi looks to be quite an undertaking, let alone RCB (or indeed any addon!) on top.

My vote on this one is WONTFIX.

**Comment by maloep** [comment]
+1 for wontfix
