### ISSUE TITLE
Nintendo Gameboy Advance not scraping game details

### ISSUE THREAD

**Issue by loggin** [maloep/romcollectionbrowser#220]
The query to http://thegamesdb.net/api/GetGame.php?name=Bomberman%20Tournament&platform=Nintendo%20Gameboy%20Advance returns an error about the platform it appears to prefer http://thegamesdb.net/api/GetGame.php?name=Bomberman%20Tournament&platform=Nintendo%20Game%20boy%20Advance, I've tweaked resources/lib/config.py within my setup to apply this change and it appears to be scraping now (not gone through the logs to see if other scrapers are working as well  now)

**Comment by bruny** [comment]
This was fixed in config.py by commit fe4c35eb1f18d2d87b7f9583860bfef38b0fdd46

**Comment by bruny** [comment]
Duplicate of #198
