### ISSUE TITLE
Use requests module for HTTP instead of urllib

### ISSUE THREAD

**Issue by bruny** [maloep/romcollectionbrowser#226]
Requests module is available for Kodi (http://kodi.wiki/view/add-on:requests) and could be used in place of urllib/urllib2 in both the scraper functions and the dbupdate.py when downloading modules.

Advantages over urllib:
- Easier support for gzip encoding as a HTTP header
- Easier parsing of responses
- Easier coding of timeout facilities and handling 4xx and 5xx response codes to determine if the remote site being scraped is down

Low priority since this is invisible to the user.

**Comment by bruny** [comment]
To tackle as part of #313

**Comment by bruny** [comment]
Implemented for scraping metadata, still need to implement for downloading images

**Comment by maloep** [comment]
This will also allow us to mock image downloading with responses library in unit tests.

**Comment by maloep** [comment]
Completed with https://github.com/maloep/romcollectionbrowser/commit/3db3e3551eed28beabcaaa2abd32e9cd4957a530
