### ISSUE TITLE
Better handling of white space

### ISSUE THREAD

**Issue by rome1983** [maloep/romcollectionbrowser#228]
When scraping games and the plot has whitespace, rcb doesn't truncate the white space. I work around this by editing the nfo and rescraping with local nfo.

**Comment by bruny** [comment]
Do you have an example of which game/collection/scraper this occurs for?

**Comment by rome1983** [comment]
http://www.mobygames.com/game/nes/super-contra
Moby games , some games are worst than this one.

**Comment by rome1983** [comment]
nfo example http://paste.ubuntu.com/19931131/

**Comment by bruny** [comment]
Code in question is stripHTMLTags() in dbupdate.py.

I'm having a look at a few options such as BeautifulSoup or html2text to see whether these give more reliable parsing options (since the plots created from giantbomb don't retain line breaks or delineate headings).

**Comment by bruny** [comment]
Look at this as part of #313 and add as a unittest case

**Comment by bruny** [comment]
Whitespace and HTML entities shouldn't be an issue with the scrapers now hitting the APIs. However we don't have a Mobygames API scraper yet (#332) so that needs to be added before this can be really closed, given that the bug was raised against a Mobygames game.

**Comment by bruny** [comment]
The Mobygames API returns HTML entities and possibly whitespace.

**Comment by maloep** [comment]
I think we can do this the other way. I added a util method "html_to_kodi()" replacing "<i>" with "[I]" and "<b>" with "[B]". This way we can leave the html tags in db and just format the text as intended when displaying it.

@bruny: please reopen if you do not like this approach.
