### ISSUE TITLE
Remove support for MAWS and archive.vg

### ISSUE THREAD

**Issue by bruny** [maloep/romcollectionbrowser#229]
Both MAWS and archive.vg have been offline for years. Keeping them as available options is misleading.

The scraper xml files, wiki references need to be updated/deleted. MAWS also has some code that is used when a MAME rom collection is added.

**Comment by maloep** [comment]
Fixed with https://github.com/maloep/romcollectionbrowser/commit/0f2fdb6a3663928646d63591176b773a9346e63c

archive.vg is still alive but has a new API, so maybe we can re-add them one day.
