### ISSUE TITLE
Mobygames doesn't always include perspective field.

### ISSUE THREAD

**Issue by martyn-harris** [maloep/romcollectionbrowser#241]
Quite often the game detail page on mobygames.com doesn't include a "Perspective" field.
Because the grammar description for mobygames expects that field to be present it results in the parsing failing, as which point the other values which are present (description, publisher, etc..) are lost.

A couple of examples of games with missing perspectives are:
[http://www.mobygames.com/game/genesis/nhl-95](http://www.mobygames.com/game/genesis/nhl-95)
[http://www.mobygames.com/game/genesis/6-pak](http://www.mobygames.com/game/genesis/6-pak)

That is just 2 examples, but there are probably 40 or so games in my collection that wont scrape through moby because of this same problem.

Due to the unpredictability of this field, and because none of the other scraper sites provide it, I'd suggest removing that field from the grammar description XML

**Comment by martyn-harris** [comment]
Corrected locally and submitted a pull request.

**Comment by maloep** [comment]
The PR was merged. Thanks for the submit.
