### ISSUE TITLE
"Make Local Copy" for Mame & NeoGeo Roms to run on Android- Missing Bios files

### ISSUE THREAD

**Issue by Spikey818** [maloep/romcollectionbrowser#250]
Need a solution for playing Mame & Neo Geo roms on an Amazon Fire TV Stick via a network share drive.  Roms are all located on a Network Share and they will copy to the tmp folder fine when using the options "Make Local Copy.".  The issue is that some of these roms require BIOS files in order for the emulator to run and when you are copying the rom to your local tmp folder using the "Make Local Copy" option, the emulator will launch but throws an error that it's unable to find the required neogeo.zip file.  Is there any way to make RCB when launching Mame or Neo Geo games, to also copy down the  neogeo.zip file as well as the rom file to the local /tmp folder that roms are ran from when using the "Make Local Copy" function?  Is there a different workaround that people are using for MAME when running Mame roms from a network share drive?  Please help!

**Comment by Spikey818** [comment]
or is there a way to keep the bios files such as neogeo.zip in the tmp folder without it getting deleted on every new launch?  If we could keep the bios files in the tmp folder without it getting deleted, this would be the most ideal solution.  Please let me know if anyone has any ideas on how to resolve this.  Thanks!

**Comment by bruny** [comment]
Not sure how we'd track the dependency some ROMs have for BIOS files, unless MAME could record that dependency.

What happens if you reference the NFS share in the emulator launch command rather than using Make Local Copy?

**Comment by maloep** [comment]
Sorry for not responding. I have seen in the forum that you have found a solution for this issue by using another emulator. So I will close this issue.
