### ISSUE TITLE
Filter by multiplayer

### ISSUE THREAD

**Issue by wanderingconfused** [maloep/romcollectionbrowser#272]
Just a feature suggestion.  The database scrapes multiplayer info for most games. It would be nice to search that in the filter.

**Comment by wanderingconfused** [comment]
I might install a second RCB to fiddle around with implementing this once every game is imported.  Who knows if I'll pull it off my python skills are terrible.

**Comment by maloep** [comment]
There is not much space in the filter pane, so adding new filters is no option. We could think about replacing one of the existing filters but I am not really convinced to do this.

A config option would be possible but we are trying to remove complextity from RCB and this would go in the opposite direction.

**Comment by maloep** [comment]
Just gave this a second thought. As the filter panel is one of the features that differentiates RCB from other Kodi game addons it might be worth to think about a config option. I.e. let the user select up to 5 db fields to use as a filter.

**Comment by maloep** [comment]
Done with #373
