### ISSUE TITLE
Remove all references to redundant option rcb_useOldAlignment in skin XML files

### ISSUE THREAD

**Issue by bruny** [maloep/romcollectionbrowser#307]
This option (also referenced in gui.py) relates to versions older than Helix. Can be deleted as long as the skin changes don't impact on UI.

**Comment by maloep** [comment]
referenced in:
- script-RCB-editromcollection.xml
- script-RCB-editscraper.xml
- script-RCB-importoptions.xml
- script-RCB-missinginfo.xml
- script-RCB-removeRC.xml

**Comment by maloep** [comment]
Fixed with https://github.com/maloep/romcollectionbrowser/commit/55f4455b3bda1c0ac670f45bdbf6bfe4b90e0758
