### ISSUE TITLE
Deprecate import dialog

### ISSUE THREAD

**Issue by bruny** [maloep/romcollectionbrowser#311]
Ideally we should remove the import dialog option since many of the controls are handled by the addon's settings. In addition we should aspire to Kodi-like importing experience where we don't have a further dialog before importing, and importing occurs in the background.

The only caveat is that for MAME collections we should be deferring to local file scrapers rather than online scrapers in order to reduce the network impact (and API key quota).

**Comment by maloep** [comment]
Hmmm. I am not sure about this. Yes, it would be great if everything could just work without much interaction but more often than not it doesn't. Even in Kodi I end up from time to time with Ember Media Manager or other tools to cleanup and fix all the errors and add missing movies that the standard scrapers (or maybe my misconfiguration) did not (correctly) find.

So, in RCB my plan to scrape games was like this: do a first scan with automatic and accurate import that should find and import 60-80% of the games (depending on filename quality). Then do additional scans with adjusted settings (other scrapers, interactive game selection, ...). At the end you can find the last missing games with the missing info filter and rescrape them again or add the missing bits manually. In this scenario the import option dialog had an important role to play as you could change scraping settings easily for every run.

Users that don't like this can even disable the import options dialog via addon settings.

**Comment by maloep** [comment]
I would like to move in the other direction and add more options to the import dialog. See #382
