### ISSUE TITLE
Move preferred scraper from Import dialog to Settings

### ISSUE THREAD

**Issue by bruny** [maloep/romcollectionbrowser#313]
The Import dialog offers a predefined option of scrapers to use for a rom collection, or the user can choose to select a different set of (up to) 3.

This should be moved to the Addon Settings dialog, and only 1 option shown (to reduce complexity).

In addition, if the user changes the list of scrapers for a rom collection, that choice is saved with the rom collection in the config.xml file, adding further complexity. We should remove this - the only real impact would be for MAME where we should defer to an offline scraping option.

**Comment by maloep** [comment]
I don't think we should do this. As stated in #311 the import options dialog is quite useful for me (and hopefully others).

If you are in the process of updating your collection you will usually do several scrapes in a row with different settings. It is very impractical if you have to go to addon settings every time you want to do a new scrape.

Tbh, I would even opt for reverting #312 and re-add the scraping mode selection :)

**Comment by maloep** [comment]
I would like to move in the other direction and add more options to the import dialog. See #382
