### ISSUE TITLE
Estuary skin compatibility

### ISSUE THREAD

**Issue by bruny** [maloep/romcollectionbrowser#317]
Some of the explicit Kodi skin settings conflict or look poor in the new Kodi Estuary skin.

Need to update the skin to better reflect the Estuary look and feel.

Example are the radio buttons - explicitly setting the height and width make them look non-standard.

**Comment by maloep** [comment]
Does it look ok for you with these settings? For me the buttons are too big with these settings. I added the radiowitdh and radioheight again and set them to 80. Results below:
![no explicit setting](https://user-images.githubusercontent.com/3010405/34577205-a4358c0c-f180-11e7-9774-1de175ad60c4.jpg)
![width and height set to 80](https://user-images.githubusercontent.com/3010405/34577208-a7f9076a-f180-11e7-9683-b10131c41f1b.jpg)

If this is looks ok for you, I will add these settings to all skin files.

**Comment by maloep** [comment]
Oh, I accidently committed this change already :)
So, if this looks weird on your system we need to find a good compromise.

**Comment by bruny** [comment]
I'm away until tomorrow, sorry I haven't replied, looks like you've been really busy!

Do we need to rename the "default" skin to Confluence and create a new Estuary specific skin? The look and feel is a bit off to me, in particular the up/down buttons for settings. I wasn't sure what to change those too - skinning is something I am not really across.

**Comment by maloep** [comment]
Haha, no problem. You usually have to wait weeks and months for my responses :)

Yes, I think renaming Confluence and rebuilding Estuary as new Default skin is the way to go. I will bundle what we have right now as new release in the next days and then maybe start working on Estuary.

**Comment by maloep** [comment]
I am nearly done with Estuary skin support. Still need some minor adjustments in Estuary and Confluence and maybe add 1-2 mor views to Estuary.

If you would like to review my work before I merge the branch you can check it here: https://github.com/maloep/romcollectionbrowser/tree/estuary

**Comment by maloep** [comment]
Done with https://github.com/maloep/romcollectionbrowser/pull/326
