### ISSUE TITLE
Add dummy online scrapers for testing

### ISSUE THREAD

**Issue by bruny** [maloep/romcollectionbrowser#325]
Need a way to simulate various failure scenarios, as well as E2E working, in the scrapers for testing.

Ideally set up 2 dummy scrapers, one returning JSON, the other XML and use pythons Simple HTTP server to have them generate responses.

**Comment by maloep** [comment]
I made some tests with responses library from here: https://github.com/getsentry/responses

https://github.com/maloep/romcollectionbrowser/blob/master/resources/tests/test_scrapers_mobygames_responses.py

This allows us to check if all urls are called as we expect during scrape process and modify every response as we like. With this we could mock a complete scrape process.

We could additionally implement callbacks and simulate error scenarios like mobygames 429 error.

**Comment by maloep** [comment]
I added some tests with responses library and think it is quite useful. Also added some tests for moby 429 error.
@bruny: please reopen if you wanted to take another direction
