### ISSUE TITLE
When scraping, prefer local artwork files

### ISSUE THREAD

**Issue by bruny** [maloep/romcollectionbrowser#343]
If an artwork file exists in an expected location when scraping, add it to the database. This way, we can remove the local artwork scraper as an explicit option when scraping.

**Comment by bruny** [comment]
Also see #292

**Comment by maloep** [comment]
local artwork scraper has been removed in: https://github.com/maloep/romcollectionbrowser/commit/26a0e708c28a564d7598efe8d6363dbbf55a8eca


https://github.com/maloep/romcollectionbrowser/commit/aa2409384f554dc2df46b2f8ee1e41c292ed97a2 and https://github.com/maloep/romcollectionbrowser/commit/38d9d98655bf28d68848677a8d204ff961564f34 also address this issue.
