### ISSUE TITLE
Update wiki pages for new scraper mechanism

### ISSUE THREAD

**Issue by bruny** [maloep/romcollectionbrowser#347]
Need to update the now-outdated wiki pages for:
* https://github.com/maloep/romcollectionbrowser/wiki/HowToAddMAMEOffline (now uses history.dat)
* https://github.com/maloep/romcollectionbrowser/wiki/ScraperDetails (update list of available scrapers)
* https://github.com/maloep/romcollectionbrowser/wiki/CreatingYourOwnDescriptionParser (no longer needed)

**Comment by maloep** [comment]
HowToAddMAMEOffline merged with https://github.com/maloep/romcollectionbrowser/wiki/UseOfflineGameDescriptions

ScraperDetails updated

CreatingYourOwnDescriptionParser removed
