### ISSUE TITLE
Mobygames API doesn't find images

### ISSUE THREAD

**Issue by bruny** [maloep/romcollectionbrowser#350]
Need to add support to finding images (covers, screenshots, etc) in MobyGames API

**Comment by maloep** [comment]
I think we can find images with extra calls like this:
https://api.mobygames.com/v1/games/{game_id}/platforms/{platform_id}/screenshots
https://api.mobygames.com/v1/games/{game_id}/platforms/{platform_id}/covers

**Comment by maloep** [comment]
I just added these calls as new method retrieve_images().
Atm I just invoke this method in standard retrieve method. Maybe we could change this later and only call retrieve_images method when we have checked if there are local images available.

I also added an additional call to 
https://api.mobygames.com/v1/games/{game_id}/platforms/{platform_id}
to retrieve platform specific release information.

**Comment by maloep** [comment]
On a second thought I would leave the call to retrieve_images() where it is. We will only be able to skip these calls if all possible artwork types are available locally. The possible artwork types could vary from scraper to scraper. So I think this would be too awkward to implement.

**Comment by maloep** [comment]
added with b9815202b061bbb655898b7279ea904a0d842b00
