### ISSUE TITLE
Fixed problem saving changes in view mode on KODIv18 RCBv2.2.3

### ISSUE THREAD

**Issue by Royusmc** [maloep/romcollectionbrowser#393]
I have been trying to fix this myself. It saves just fine on kodi 17.6 when I change the view mode or set the favorites. But not on kodi 18.0. I was hoping it would be fixed in the final release but it is still not working. I am using retroarch if that matters. When I set a game as favorites it works just fine and remembers the game as a favorite. But not when I change the view mode or the favorites. I have created a really nice skin for confluence but not sure where to share such stuff at. Please any help would be very nice. Thanks in advance.

**Comment by Kupo91** [comment]
I have the same issue. It saves the view mode as long as I dont leave rcb. Also launching games is no issue it keeps the view mode. Only after reopening rcb it shows the old view. Even when the settings file shows a different view mode.

**Comment by Royusmc** [comment]
Ok it took forever but I did find a fix and I just wanted to share.
In location
kodi\addons\script.games.rom.collection.browser\resources\lib\gui.py
Just change this
        #reset view mode
        viewModeId = self.Settings.getSetting(util.SETTING_RCB_VIEW_MODE)
        if viewModeId != None and viewModeId != '':
            xbmc.executebuiltin("Container.SetViewMode(%i)" % int(viewModeId))
To this
        #reset view mode
        viewModeId = self.Settings.getSetting(util.SETTING_RCB_VIEW_MODE)
        if viewModeId != None and viewModeId != '':
            xbmc.executebuiltin("Container.SetViewMode(%i)" % int(viewModeId))
            xbmc.executebuiltin("Container.SetViewMode(%i)" % int(viewModeId))
I know this should not work but give it a try. Just Doubling that line got it to work for me.
I hope this helps someone. Good luck

**Comment by maloep** [comment]
Thanks a lot for the fix. I will add this to the next release.

**Comment by maloep** [comment]
Fixed in 88a6e96
Will be released with 2.2.4
