### ISSUE TITLE
Is there French scrappers ?

### ISSUE THREAD

**Issue by nonobio** [maloep/romcollectionbrowser#397]
Hi,
 I checked scrappers used by RCB and they are all in english.
In france, i often use "[Senscritique](https://www.senscritique.com/jeuxvideo)" to find relevant games information but i don't know if it has an API and if it is compatible with RCB ?
Do you think you could add others language scrappers ?

Thanks

**Comment by maloep** [comment]
Sorry, no. I would add non-english scrapers if someone provides one. But I don't have the time to implement them myself.

**Comment by nonobio** [comment]
Thanks for your reply, and your great work :)
