### ISSUE TITLE
Adjust thegamesdb scapper for RomCenter default file names

### ISSUE THREAD

**Issue by bell07** [maloep/romcollectionbrowser#398]
I manage my roms collection using the https://www.romcenter.com/ that can rename files uniform.
For example, the "Mario64.z64" is renamed to "Super Mario 64 (Europe) (En,Fr,De).z64" by the tool.

After renaming the thegamesdb cannot find any artwork for the file anymore. Assume the "(Europe) (En,Fr,De)" needs to be ignored or used in other way.

I use the Version 2.1.3 from Kodi Add-on repository

**Comment by Kupo91** [comment]
You can create folders for your roms and give them the correct game names. Just enable the folder fuction in the addon settings.

By the way the kodi addon repo doesn't include the latest RCB version (2.2.3).
Download it here https://forum.kodi.tv/showthread.php?tid=70115

**Comment by bell07** [comment]
Thank you for the hint with the latest version. I updated the add-on to 2.2.3.

I do not like to manage the folder/files naming manually, for that reason I use the manager-tool. My feature request is the scapper should be able to use the names given by the tool. Maybe something like `sed 's/(.*)//g'`

**Comment by maloep** [comment]
RCB should already ignore additional info in brackets. Maybe it has an issue with multiple infos in brackets. I have to look into it.

**Comment by maloep** [comment]
Fixed in 1f08937
Will be released with 2.2.4
