### ISSUE TITLE
Local (game-database-info) scraping fails for games with apostrophe

### ISSUE THREAD

**Issue by nitro322** [maloep/romcollectionbrowser#403]
I'm scraping my games with the Game-database-info scraper, using the XML files provided by billyc999 as recommended in the documentation.  It generally works fine, but if the game has an apostrophe in the title (Such as Yars' Revenge), info scraping files.  The game still shows up and all local artwork is still recognized, but I can't get it to match the info file.

I suspect it has to do with the apostrophe being represented as an HTML entity in the XML file.  Ie.:

>   &lt;game name="Yars&amp;apos; Revenge (USA)"&gt;
>     &lt;description&gt;Yars&amp;apos; Revenge&lt;/description&gt;

I tried changing it to "Yars' Revenge" explicitly, but still couldn't get a match.  I then dropped the apostrophe and renamed the file to just "Yars Revenge" revenge, and it matched fine.  Added the apostrophe back, and it fails again.

This seems like a common enough problem that I'm surprised I don't see an issue already reported on this.  I may be doing something obviously wrong (and if so, please point it out!), but based on my testing above it appears to simply not handle apostrophes correctly.

Would appreciate if someone could look into this when they get the change.  Thanks!

**Comment by maloep** [comment]
Fixed with 3a24bd1f44b3e4047801dc75c89c86cdb2f1df92
