### ISSUE TITLE
Genesis web_scraper not working

### ISSUE THREAD

**Issue by ochi-man** [maloep/romcollectionbrowser#415]
The number of parameters is wrong, removing the 6 or 31 it will work fine for TGDB (18 at the 4 position)
 
https://github.com/maloep/romcollectionbrowser/blob/dd2190558803f21d18a053e0dd65752345f4c02b/resources/lib/pyscraper/web_scraper.py#L86

**Comment by maloep** [comment]
Thanks for the hint.
Fixed with 9a0b71a6b0306d83294d56f84f49077b0d4e373b
Updated master (Matrix) and Leia branch
