### ISSUE TITLE
Cant run windows games on linux

### ISSUE THREAD

**Issue by ochi-man** [maloep/romcollectionbrowser#416]
last time i tried, the RCB say something about incompatible platform, but a lot of games works great with wine, if it is possible i would ask to add the option for launch windows and android (a pretty simple script and anbox and you can run a lot of things), in a linux install.

**Comment by maloep** [comment]
Can you tell me when you get this message (during configuration, import, launching) and maybe the exact message text?

I was looking where in the code I could have added this limitation but I could not find it.

**Comment by ochi-man** [comment]
It was when launch the game, i put the rom file as .sh, i made this way so i can set the right bottle for each game, as soon i have the time i will test again.
In the library it works fine, and even get the images and info online, without a problem.

**Comment by ochi-man** [comment]
i really sorry, it was some mistake mine, i test here and work.

I believe  i may have selected use retroplayer by mistake kkkk.

sorry for the trouble and time, and thanks for the fixes on the other issues.
