### ISSUE TITLE
[matrix branch] xbmc.abortRequested not available on Matrix

### ISSUE THREAD

**Issue by XayOn** [maloep/romcollectionbrowser#428]
Monitor().abortRequested() should be enough.
I propose the removal of xbmc.abortRequested.

**Comment by XayOn** [comment]
Seems like the fix I made in my PR breaks the cancel option, but at least it starts up

**Comment by XayOn** [comment]
Seems like the fix I made in my PR breaks the cancel option, but at least it starts up

**Comment by maloep** [comment]
Fixed with ef82f829fa53deb8665b1f03bac814b86c5a2528
