### ISSUE TITLE
Matrix branch: launching RCB breaks castagnait netflix plugin

### ISSUE THREAD

**Issue by 7opf** [maloep/romcollectionbrowser#431]
I followed [instructions](https://forum.kodi.tv/showthread.php?tid=70115&pid=2937200#pid2937200) to install the matrix branch of RCB which works fine and I can also launch RCB afterwards. 

I noticed, however that after the first launch of RCB, the netflix add on stops working ([fails to launch](https://github.com/CastagnaIT/plugin.video.netflix/issues/1061)). You can see in the linked stack trace that the netflix plugin is executing something in RCB directory, not sure how this can happen.

**Comment by 7opf** [comment]
CastagnaIt has kindly given a potential explanation here: https://github.com/CastagnaIT/plugin.video.netflix/issues/1061#issuecomment-774470523

**Comment by maloep** [comment]
Thanks for the PR. I will test and include it asap.

**Comment by louisefindlay23** [comment]
Seems to be a similar issue with PlexKodiConnect. https://github.com/croneter/PlexKodiConnect/issues/1425

**Comment by maloep** [comment]
Fixed with https://github.com/maloep/romcollectionbrowser/pull/432
