### ISSUE TITLE
Upgrade req's for Matrix version

### ISSUE THREAD

**Issue by grnassar** [maloep/romcollectionbrowser#433]
Please forgive me if I did a poor job for searching for this and the answer is already here somewhere.

If I'm running the standard build of RCB, and I'm about to upgrade to Kodi Matrix and the Matrix-compatible version of RCB, is there anything special I need to do? Can I just upgrade RCB in-place, or should I uninstall the old one? Delete the existing ROM collection user info or leave it there? Etc. Just any caveats or warnings that would be good to know prior to the upgrade would be useful. Thank you!

**Comment by maloep** [comment]
It should be possible to update RCB in-place. No need to delete anything. You should make a backup of your config.xml and MyGames.db first.
